version: 0.1

phases:
  pre_build:
    commands:
      - pip install cython numpy
      - pip install -r requirements.txt
      - python -m unittest discover -v

artifacts:
  type: zip
  files:
    - '.ebextensions/**/*'
    - 'traffic_lights/**/*'
    - 'application.py'
    - 'requirements.txt'