version: 0.3

phases:
  pre_build:
    commands:
      - python -m unittest discover -v

artifacts:
  type: zip
  files:
    - '.ebextensions/**/*'
    - 'traffic_lights/**/*'
    - 'application.py'
    - 'requirements.txt'