version: 0.1

phases:
  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.pytest.org/en/latest/goodpractices.html>
      - pip install -r requirements.txt
      - python -m unittest discover -v

artifacts:
  type: zip
  files:
    - 'api/**/*.py'
    - 'traffic_lights/**/*'
    - 'requirements.txt'